### PR TITLE
Removing outdated community-voting.md, DAO user guide page replaces t…

### PR DESCRIPTION
**Pull request by mattimus5460**
Community members have noticed out of date information on the DAO documentation pages.

This PR is intended to address outdated information as well as add updated information with changes from the last few months. EX: L1 wearable VP calcs, removing references to wrapped mana for voting

### CODE REVIEW

**Comment by mattimus5460** [comment]
https://docs.decentraland.org/player/general/dao/overview/what-smart-contracts-does-the-dao-control/  are we able to provide the contract addresses on this page?

**Comment by menduz** [comment]
what replaces this information? we should redirect people accessing this link to some other place to find the information they need

**Comment by mattimus5460** [comment]
@menduz the info on community voting is the same topics as the Dao user guide. The Dao user guide page can be the redirect location. Is the redirect done in markdown? Is there an existing redirect example?

**Comment by menduz** [comment]
Yes, there are many, I think it is `redirect_from` in the matterfront of the target file

**Comment by mattimus5460** [comment]
@menduz I could not find any example searching for "redirect", but I have added an alias with the deleted page url to the dao-user-guide page

**Comment by menduz** [comment]
I think that should be it! Thank you!

**Pull request merged**
