### PR TITLE
publishing options

### PR DESCRIPTION
**Pull request by nearnshaw**

### CODE REVIEW

**Comment by menduz** [comment]
Maybe add a link to WORLDs??

**Comment by nearnshaw** [comment]
> Maybe add a link to WORLDs??

yep, it's included there, but commented out
when worlds is in beta and the worlds section in the doc is merged and published I want to uncomment that bit

**Comment by menduz** [comment]
it was alreadyy

**Comment by nearnshaw** [comment]
It just got merged minutes ago
so now I included the mentions to worlds :D

**Pull request merged**
