### PR TITLE
Add Organizational Chart to DAO Documentation

### PR DESCRIPTION
**Pull request by TweebitAI**
Due to DCL DAO governance proposal:
https://decentraland.org/governance/proposal/?id=c942aa60-443c-11ee-ab1f-97157a05bdec

### CODE REVIEW

**Comment by ginocingolani** [comment]
@lordlikedao I'd recommend updating the How the DAO Works article with committees and org charts. Also, it would be better if the images were stored in the images folder on this repo https://github.com/decentraland/documentation/blob/main/images

**Comment by TweebitAI** [comment]
@nearnshaw Could you please review this PR ?

**Review by nearnshaw — APPROVED** [review]

**Comment by nearnshaw** [comment]
@lordlikedao approved!

**Comment by TweebitAI** [comment]
@nearnshaw Hey, thanks with a quick respond and approve.

As far as I know, approved doesn’t mean closed. This pull request is still opened and it means that changes have not been merged into the branch yet, right? 

Cause I can’t see the suggested folder with photos in the “images” folder in the main brunch. And the last update there was three days ago. 

Could you please let me know what else is needed to close the pull request, so these changes appear in the Decentraland documentation repository?

**Comment by nearnshaw** [comment]
@lordlikedao  right, approved doesn't mean the changes are published. For that, you need to press the "Squash and merge" green button that appears in this screen. After that, the build process can last a few minutes, and then the site should be updated.

**Comment by TweebitAI** [comment]
@nearnshaw  I don't have access to press the "Squash and merge". I have only close pull request button. Could you please do it ?

**Comment by nearnshaw** [comment]
@lordlikedao  done!

**Pull request merged**
